apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-go-web2git
  labels:carto.run/workload-name: hello-go-web2git
    app.kubernetes.io/component: run
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
    spec:
      containers:
        - name: workload
          image: us-east4-docker.pkg.dev/fe-ciberkleid/cartographer-demo/hello-go-web2git@sha256:86e3eadc487361b520de95c3e6894b011fa65736d0dfce106bdb4536fe7a3a61
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 1000
      imagePullSecrets:
        - name: service-account
