apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dev
  labels:
    app.kubernetes.io/part-of: hello-world
    carto.run/workload-name: dev
    app.kubernetes.io/component: run
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
    spec:
      containers:
        - name: workload
          image: gcr.io/fe-ciberkleid/carto-demo/dev@sha256:b3ac23f8ccdba35d02dfb3c0171dc25ce591e298605b67462586cd4486980c82
          securityContext:
            runAsUser: 1000
      imagePullSecrets:
        - name: registry-credentials

