---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
rebaseRules:
  - path:
      - metadata
      - annotations
      - serving.knative.dev/creator
    type: copy
    sources: [new, existing]
    resourceMatchers: &matchers
      - apiVersionKindMatcher:
          apiVersion: serving.knative.dev/v1
          kind: Service
  - path:
      - metadata
      - annotations
      - serving.knative.dev/lastModifier
    type: copy
    sources: [new, existing]
    resourceMatchers: *matchers
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: $(workload.metadata.name)$
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
      labels:
        app.kubernetes.io/part-of: $(workload.metadata.name)$
    spec:
      serviceAccountName: service-account
      containers:
        - name: workload
          image: $(image)$
          env: $(workload.spec.env)$
          ports:
            - containerPort: $(params.containerPort)$
          securityContext:
            runAsUser: 1000