apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dev
  labels:
    app.kubernetes.io/part-of: hello-world
    carto.run/workload-name: dev
    app.kubernetes.io/component: run
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
    spec:
      containers:
        - name: workload
          image: gcr.io/fe-ciberkleid/carto-demo/dev@sha256:92eb05ea069144492cb1b64ba156051bfeeddccaf3e73d00d1031f601dbb5037
          securityContext:
            runAsUser: 1000
      imagePullSecrets:
        - name: registry-credentials

